# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/knowledge_graphs',
                'doc_host': 'https://tonirodriguez.github.io',
                'git_url': 'https://github.com/tonirodriguez/knowledge_graphs',
                'lib_path': 'knowledge_graphs'},
  'syms': {'knowledge_graphs.ner': {}}}