# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_ner.ipynb.

# %% auto 0
__all__ = []

# %% ../00_ner.ipynb 5
import spacy
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('./data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


